"""create tables

Revision ID: 172a6ee7b2a6
Revises: 
Create Date: 2023-02-23 22:56:10.999967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172a6ee7b2a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opticalindex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('wavelength', sa.Float(), nullable=True),
    sa.Column('n', sa.Float(), nullable=True),
    sa.Column('k', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opticalindex')
    op.drop_table('material')
    # ### end Alembic commands ###
